-- CreateTable
CREATE TABLE "Todo" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Content" TEXT NOT NULL,
    "completed" BOOLEAN NOT NULL DEFAULT false
);
